extends: airbnb-base
plugins:
  - import
rules:
  no-console: off
  indent:
    - error
    - 4
  no-restricted-syntax: off
  no-await-in-loop: off
  import/no-extraneous-dependencies: off
  import/no-unresolved: off
  max-len:
    - error
    - code: 145
